filePaths = ["testpath1.txt", "testpath2.txt"]
senderEmail = "test@example.com"
senderPassword = "testpassword"
subject = "Test Subject"
body = "Test Body"
[[receivers]]
name = "Test Receiver"
email = "receiver@test.com"
